import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'
import Panel from './SerialSequencePanel.vue'
const props = () => ({ statuses: {}, port: 'A', running: true, busy: false, error: '' })
describe('reader-owned sequence controls', () => {
  it('submits an immutable ordered draft with explicit cycles and selected port', async () => {
    const w = mount(Panel, { props: props() })
    await w.get('[data-testid="sequence-command"]').setValue('Q\n')
    await w.get('[data-testid="sequence-add"]').trigger('click')
    await w.findAll('textarea')[1]!.setValue('00 ff')
    await w.findAll('select')[1]!.setValue('true')
    await w.get('[data-testid="sequence-repeat"]').setValue(2)
    await w.get('[data-testid="sequence-start"]').trigger('click')
    expect(w.emitted('start')?.[0]).toEqual([{port:'A',commands:[{data:'Q\n',hex:false},{data:'00 ff',hex:true}],interval_ms:1000,repeat:2}])
    await w.findAll('textarea')[0]!.setValue('new draft')
    expect((w.emitted('start')![0]![0] as any).commands[0].data).toBe('Q\n')
    w.unmount()
    expect(w.emitted('stop')).toBeUndefined()
  })
  it('locks only the selected active port and stops the named row after selection changes', async () => {
    const w = mount(Panel, { props: {...props(), statuses:{A:{state:'running',active:true,sent:3},B:{state:'failed',active:false,sent:1,error:'partial write'}}} })
    expect(w.get('[data-testid="sequence-command"]').attributes('disabled')).toBeDefined()
    await w.setProps({port:'B'})
    expect(w.get('[data-testid="sequence-command"]').attributes('disabled')).toBeUndefined()
    await w.get('tr[data-port="A"] button').trigger('click')
    expect(w.emitted('stop')).toEqual([['A']])
    expect(w.get('tr[data-port="B"]').text()).toContain('partial write')
    w.unmount()
  })
  it('rejects empty, invalid timing, and oversized drafts without emitting', async () => {
    const w=mount(Panel,{props:props()})
    await w.get('[data-testid="sequence-start"]').trigger('click')
    expect(w.get('[role="alert"]').exists()).toBe(true)
    await w.get('[data-testid="sequence-command"]').setValue('x')
    await w.get('[data-testid="sequence-interval"]').setValue(19)
    await w.get('[data-testid="sequence-start"]').trigger('click')
    await w.get('[data-testid="sequence-interval"]').setValue(20)
    await w.get('[data-testid="sequence-command"]').setValue('中'.repeat(6000))
    await w.get('[data-testid="sequence-start"]').trigger('click')
    expect(w.emitted('start')).toBeUndefined()
    w.unmount()
  })
  it('does not dispatch while disconnected or an operation is pending', async () => {
    const w=mount(Panel,{props:{...props(),running:false}})
    expect(w.get('[data-testid="sequence-start"]').attributes('disabled')).toBeDefined()
    await w.setProps({running:true,busy:true,statuses:{A:{state:'running',active:true}}})
    expect(w.get('tr[data-port="A"] button').attributes('disabled')).toBeDefined()
    w.unmount()
  })
})
